[package]
name = "novelize"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
dotenvy = "0.15.7"
google-ai-rs = "0.3.0"
regex = "1.13.1"
reqwest = "0.13.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
strum = { version = "0.28.0", features = ["derive"] }
tokio = "1.53.1"
