mod generation;
mod story;
mod etc;
use etc::{copy_dir_all, clean_code_block_wrappers};
use std::error::Error;
use std::fs;
use std::path::Path;
use google_ai_rs::Client;
use crate::pipeline::generation::outlining::generate_storyboard;
use crate::renpy::run_renpy_lint;


const EXPENSIVE_MODEL: &str = "gemini-3.5-flash-lite";
const CHEAP_MODEL: &str = "gemini-3.5-flash-lite";

pub async fn run_pipeline(
    client: &Client,
    topic: &str,
    base_dir: &Path,
    output_game_dir: &Path,
    max_fix_attempts: u8,
    sdk_path: &Path,
) -> Result<(), Box<dyn Error>> {
    let char_info = fs::read_to_string(base_dir.join("data/character_info.txt"))?;

    println!("[1/4] Generating structured Storyboard Outline...");
    
    let storyboard = generate_storyboard(
        EXPENSIVE_MODEL, 
        client, 
        topic,
        &char_info
    ).await?;

    // Create target game folder by copying our template project
    if output_game_dir.exists() {
        let _ = fs::remove_dir_all(&output_game_dir);
    }
    
    copy_dir_all(
        base_dir.join("templates/template_project"),
        &output_game_dir,
    )?;

    let scenes_dir = output_game_dir.join("game/scenes");
    fs::create_dir_all(&scenes_dir)?;

    let mut prev_scene_summary: Option<String> = None;
    let mut scene_ids = Vec::new();

    for (index, scene) in storyboard.scenes.iter().enumerate() {
        println!(
            "[2/4] Generating Scene {}/{} [{}]: {}...",
            index + 1,
            storyboard.scenes.len(),
            scene.id,
            scene.title
        );

        let script = generation::scenes::generate_scene(
            CHEAP_MODEL, 
            client, 
            &scene, 
            prev_scene_summary, 
            &char_info
        ).await?;

        let scene_file_name = format!("{}.rpy", scene.id);
        fs::write(scenes_dir.join(&scene_file_name), &script)?;

        prev_scene_summary = Some(scene.summary.clone());
        scene_ids.push(scene.id.clone());
    }

    println!("[3/4] Assembling script.rpy...");
    let mut script_content = String::new();
    script_content.push_str(
        r#"# Automatically generated by Novelize: https://github.com/niko-at-chalupa/novelize
label start:
"#,
    );

    for (index, id) in scene_ids.iter().enumerate() {
        if index == 0 {
            script_content.push_str(&format!("    # Begin visual novel\n    call {}\n", id));
        } else {
            script_content.push_str(&format!("    call {}\n", id));
        }
    }
    script_content.push_str("    return\n");

    fs::write(output_game_dir.join("game/script.rpy"), script_content)?;

    println!("[4/4] Verifying generated project with Ren'Py lint...");

    for attempt in 1..=max_fix_attempts {
        let lint_output = run_renpy_lint(&sdk_path, &output_game_dir)?;
        if lint_output.status.success() {
            println!("[4/4] Lint passed on attempt {}.", attempt);
            break;
        }

        if attempt == max_fix_attempts {
            return Err(format!(
                "Ren'Py lint still failing after {} fix attempts:\n{}",
                max_fix_attempts,
                String::from_utf8_lossy(&lint_output.stdout)
            )
            .into());
        }

        let lint_report = format!(
            "{}\n{}",
            String::from_utf8_lossy(&lint_output.stdout),
            String::from_utf8_lossy(&lint_output.stderr)
        );

        println!(
            "[4/4] Lint failed (attempt {}/{}). Diagnosing affected scenes...",
            attempt, max_fix_attempts
        );

        let affected = generation::linting::triage_lint_errors(EXPENSIVE_MODEL, client, &lint_report, &scene_ids).await?;
        if affected.is_empty() {
            return Err(format!(
                "Lint failed but triage identified no fixable scene files:\n{}",
                lint_report
            )
            .into());
        }

        for scene_id in &affected {
            println!("[4/4]   Repairing scene: {}", scene_id);
            generation::linting::fix_scene_file(EXPENSIVE_MODEL, client, &scenes_dir, scene_id, &lint_report).await?;
        }
    }

    Ok(())
}