mod etc;
mod generation;
mod story;
use crate::template::TemplateVn;
use crate::pipeline::generation::outlining::generate_storyboard;
use crate::renpy::run_renpy_lint;
use etc::{clean_code_block_wrappers, copy_dir_all};
use google_ai_rs::Client;
use tracing::info;
use std::error::Error;
use std::fs;
use std::path::Path;

const EXPENSIVE_MODEL: &str = "gemini-3.5-flash-lite";
const CHEAP_MODEL: &str = "gemini-3.5-flash-lite";

fn copy_template_directory(src: &Path, dst: &Path) -> std::io::Result<()> {
    if !src.exists() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            format!("template directory does not exist: {}", src.display()),
        ));
    }

    copy_dir_all(src, dst)?;
    Ok(())
}

pub async fn run_pipeline(
    client: &Client,
    topic: &str,
    template_game_dir: &Path,
    output_game_dir: &Path,
    max_fix_attempts: u8,
    sdk_path: &Path,
    num_scenes: u8,
) -> Result<(), Box<dyn Error>> {
    info!("[1/5] Validating template VN");

    let template = TemplateVn::load(template_game_dir)?;
    let extra_context = generation::ExtraContext {
        narrative: template
            .paths()
            .context_narrative()
            .iter()
            .map(|path| fs::read_to_string(template_game_dir.join(path)))
            .collect::<Result<_, _>>()?,
        dialogue: template
            .paths()
            .context_dialogue()
            .iter()
            .map(|path| fs::read_to_string(template_game_dir.join(path)))
            .collect::<Result<_, _>>()?,
        visuals: template
            .paths()
            .context_visuals()
            .iter()
            .map(|path| fs::read_to_string(template_game_dir.join(path)))
            .collect::<Result<_, _>>()?,
        storyboard_system: read_optional_template_file(
            template_game_dir,
            template.paths().prompts.storyboard_system.as_deref(),
        )?,
        storyboard_prompt: read_optional_template_file(
            template_game_dir,
            template.paths().prompts.storyboard_prompt.as_deref(),
        )?,
        scene_system: read_optional_template_file(
            template_game_dir,
            template.paths().prompts.scene_system.as_deref(),
        )?,
        scene_prompt: read_optional_template_file(
            template_game_dir,
            template.paths().prompts.scene_prompt.as_deref(),
        )?,
    };
    info!("Checking if the template game is valid...");
    template.is_game_valid(template_game_dir, sdk_path.to_path_buf())?;

    info!("[2/5] Generating structured Storyboard Outline...");

    let storyboard = generate_storyboard(
        EXPENSIVE_MODEL,
        client,
        topic,
        &extra_context,
        num_scenes,
    )
    .await?;

    // Create target game folder by copying our template project
    if output_game_dir.exists() {
        let _ = fs::remove_dir_all(output_game_dir);
    }

    copy_template_directory(template_game_dir, output_game_dir)?;

    let scenes_dir = output_game_dir.join("game/scenes");
    fs::create_dir_all(&scenes_dir)?;

    let mut prev_scene_summary: Option<String> = None;
    let mut scene_ids = Vec::new();

    for (index, scene) in storyboard.scenes.iter().enumerate() {
        info!(
            "[3/5] Generating Scene {}/{} [{}]: {}...",
            index + 1,
            storyboard.scenes.len(),
            scene.id,
            scene.title
        );

        let script = generation::scenes::generate_scene(
            CHEAP_MODEL,
            client,
            scene,
            prev_scene_summary,
            &extra_context,
        )
        .await?;

        let scene_file_name = format!("{}.rpy", scene.id);
        fs::write(scenes_dir.join(&scene_file_name), &script)?;

        prev_scene_summary = Some(scene.summary.clone());
        scene_ids.push(scene.id.clone());
    }

    info!("[4/5] Assembling script.rpy...");
    let mut script_content = String::new();
    script_content.push_str(
        r#"# Automatically generated by Novelize: https://github.com/niko-at-chalupa/novelize
label start:
"#,
    );

    for (index, id) in scene_ids.iter().enumerate() {
        if index == 0 {
            script_content.push_str(&format!("    # Begin visual novel\n    call {}\n", id));
        } else {
            script_content.push_str(&format!("    call {}\n", id));
        }
    }
    script_content.push_str("    return\n");

    fs::write(output_game_dir.join("game/script.rpy"), script_content)?;

    info!("[5/5] Verifying generated project with Ren'Py lint...");

    for attempt in 1..=max_fix_attempts {
        let lint_output = run_renpy_lint(sdk_path, output_game_dir)?;
        if lint_output.status.success() {
            info!("[5/5] Lint passed on attempt {}.", attempt);
            break;
        }

        if attempt == max_fix_attempts {
            return Err(format!(
                "Ren'Py lint still failing after {} fix attempts:\n{}",
                max_fix_attempts,
                String::from_utf8_lossy(&lint_output.stdout)
            )
            .into());
        }

        let lint_report = format!(
            "{}\n{}",
            String::from_utf8_lossy(&lint_output.stdout),
            String::from_utf8_lossy(&lint_output.stderr)
        );

        info!(
            "[5/5] Lint failed (attempt {}/{}). Diagnosing affected scenes...",
            attempt, max_fix_attempts
        );

        let affected = generation::linting::triage_lint_errors(
            EXPENSIVE_MODEL,
            client,
            &lint_report,
            &scene_ids,
        )
        .await?;
        if affected.is_empty() {
            return Err(format!(
                "Lint failed but triage identified no fixable scene files:\n{}",
                lint_report
            )
            .into());
        }

        for scene_id in &affected {
            info!("[4/4]   Repairing scene: {}", scene_id);
            generation::linting::fix_scene_file(
                EXPENSIVE_MODEL,
                client,
                &scenes_dir,
                scene_id,
                &lint_report,
            )
            .await?;
        }
    }

    Ok(())
}

fn read_optional_template_file(root: &Path, path: Option<&Path>) -> std::io::Result<String> {
    path.map(|path| fs::read_to_string(root.join(path)))
        .transpose()
        .map(|content| content.unwrap_or_default())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn copies_custom_template_directory() -> std::io::Result<()> {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root = std::env::temp_dir().join(format!("novelize-template-test-{unique}"));
        let template_dir = root.join("template");
        let output_dir = root.join("output");

        fs::create_dir_all(template_dir.join("game"))?;
        fs::write(template_dir.join("game/test.rpy"), "label start:\n")?;

        copy_template_directory(&template_dir, &output_dir)?;

        assert!(output_dir.join("game/test.rpy").exists());
        let script = fs::read_to_string(output_dir.join("game/test.rpy"))?;
        assert_eq!(script, "label start:\n");

        fs::remove_dir_all(&root)?;
        Ok(())
    }
}
